import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import { CategoryProvider } from "@/context/CategoryContext";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: "--font-poppins"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}`}
      >
        <div className="mx-auto max-w-screen-lg">
          <CategoryProvider>
            <div className="flex min-h-screen flex-col">
              {children}
            </div>
          </CategoryProvider>
          
        </div>
      </body>
    </html>
  );
}
